import json
import os

base_dir = r"C:\Users\CartridgeStack\Qwen-Tokenizer-Pruner\sample_data"
os.makedirs(base_dir, exist_ok=True)

def write_json(idx, query, response):
    path = os.path.join(base_dir, f"{idx}.json")
    data = {"query": query, "response": response}
    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

langs = ["EN", "ES", "PT", "FR", "IT", "RO", "DE"]

ai_templates = [
    # Prompting / Prompt Engineering
    ("{lang}: Explain the 'chain-of-thought' prompting technique and when it improves LLM reasoning.", "Chain-of-thought (CoT) prompting instructs the model to emit intermediate reasoning steps before the final answer. It significantly improves performance on arithmetic, symbolic logic, and multi-step problems by decomposing the task. Zero-shot CoT uses triggers like 'Let's think step by step,' while few-shot CoT provides explicit reasoning exemplars in the context."),
    ("{lang}: ¿Qué es el 'few-shot prompting' y cómo afecta la calidad de las respuestas de un LLM?", "El few-shot prompting incluye ejemplos de entrada-salida en el contexto antes de la consulta real. Actúa como aprendizaje en contexto, permitiendo al modelo inferir el formato, estilo y patrones lógicos deseados sin actualizar pesos. Generalmente 3-5 ejemplos bien seleccionados superan el zero-shot en tareas de clasificación y transformación."),
    ("{lang}: O que é 'system prompt injection' e como mitigá-lo em aplicações de produção?", "System prompt injection ocorre quando o usuário insere instruções maliciosas que sobrescrevem o comportamento desejado (ex: 'ignore previous instructions'). Mitigações: separação clara de roles (system vs user), filtragem de entrada, uso de delimitadores estruturados (XML/JSON), e modelos com maior robustez a jailbreaks via fine-tuning de rejeição."),
    ("{lang}: Comment structurer un prompt pour extraire des entités nommées au format JSON strict?", "Utilisez un prompt système définissant le schéma JSON attendu avec des types et contraintes. Dans le prompt utilisateur, fournissez le texte brut entouré de balises XML (ex: <texte>...</texte>). Demandez explicitement 'Réponds uniquement avec un objet JSON valide, sans texte supplémentaire'. Utilisez un seed bas et temperature=0 pour la reproductibilité."),
    ("{lang}: Descrivi la tecnica del 'role prompting' per ottenere risposte specializzate da un LLM.", "Nel role prompting si assegna al modello un'identità specifica nel system prompt, ad esempio 'Sei un esperto ingegnere del software con 20 anni di esperienza in sistemi distribuiti'. Questo attiva pattern di conoscenza associati al ruolo, migliorando la precisione tecnica e il tono professionale della risposta."),
    ("{lang}: Cum funcționează 'prompt tuning' comparativ cu fine-tuningul complet al unui model?", "Prompt tuning adaugă token-uri soft (embeddings antrenați) la intrare în loc să modifice parametrii modelului. Necesită doar câteva mii de parametri extra vs. miliarde la fine-tuning. Este mai rapid și mai eficient din punct de vedere computațional, dar poate fi mai puțin puternic decât fine-tuningul complet pentru sarcini complexe."),
    ("{lang}: Erkläre das Konzept 'Retrieval-Augmented Generation' (RAG) und seine Vorteile gegenüber einem großen Kontextfenster.", "RAG kombiniert Information Retrieval mit Textgenerierung: relevante Dokumente werden aus einer Vektordatenbank abgerufen und in den Prompt eingefügt. Vorteile gegenüber riesigem Kontextfenster: geringere Inferenzkosten, aktuellere Daten, bessere Quellenangaben (Attribution), und Vermeidung von Halluzinationen durch grounding in externem Wissen."),

    # Tokens / Tokenization
    ("{lang}: How do you estimate token count for a mixed English/Chinese text before calling an API?", "A rough heuristic is 1 token ≈ 0.75 words for English and 1 token ≈ 1 character for Chinese. For precise counts, use the official tokenizer (e.g., tiktoken for GPT-4, Hugging Face tokenizers for open models). Always count the full prompt including system messages, function schemas, and historical turns to avoid context window overflow."),
    ("{lang}: ¿Cuál es la diferencia entre BPE, WordPiece y SentencePiece en tokenización para LLMs?", "BPE (Byte Pair Encoding) fusiona pares de bytes frecuentes iterativamente (GPT, Llama). WordPiece usa un criterio de máxima verosimilitud (BERT). SentencePiece trata el texto como una secuencia de Unicode y puede tokenizar sin espacios (T5, Llama 2+). Todos producen vocabularios subword que equilibran tamaño de vocabulario y capacidad de representar palabras raras."),
    ("{lang}: Explique o impacto do 'context window' de 128k tokens na arquitetura de um agente de IA.", "Janelas de 128k tokens (ex: GPT-4, Gemini) permitem agentes com memória de conversação longa e RAG em documentos extensos. O desafio é a degradação de atenção em tokens distantes (lost in the middle) e o custo quadrático de memória do attention clássico. Soluções incluem Ring Attention, sparse attention, e hierarquias de resumo."),
    ("{lang}: Qu'est-ce que le 'KV cache' et pourquoi est-il le principal consommateur de VRAM pendant l'inférence?", "Le KV cache stocke les tenseurs key et value de chaque couche d'attention pour tous les tokens précédents. Sa taille croît linéairement avec la longueur de la séquence et le batch size. Pour un modèle 70B en fp16, le KV cache peut dépasser plusieurs gigaoctets par séquence longue, dominant souvent la mémoire par rapport aux poids du modèle eux-mêmes."),
    ("{lang}: Come si calcola il numero massimo di token generabili dati i vincoli di VRAM disponibili?", "La VRAM totale richiesta è: pesi_modello + KV_cache + overhead_attivazione. Per modelli quantizzati (es. Q4_K_M), i pesi occupano ~0.5 bytes per parametro. Il KV_cache si calcola come 2 * num_layers * num_heads * head_dim * seq_len * batch_size * precisione_bytes. Sottraendo i pesi dalla VRAM disponibile si ottiene il budget per batch e lunghezza di sequenza."),
    ("{lang}: Ce înseamnă 'truncation' și 'padding' în contextul tokenizării pentru un model transformer?", "Truncation taie secvențele mai lungi decât max_length pentru a încăpea în context window. Padding adaugă token-uri speciale (PAD) pentru a uniformiza lungimea într-un batch. Strategiile de truncation includ 'left' (păstrează finalul, util pentru generare) și 'right' (păstrează începutul, util pentru clasificare). Padding-ul trebuie mascat în attention pentru a nu afecta logits."),

    # Weights / Parameters / Quantization
    ("{lang}: What is the difference between INT8, INT4, and GPTQ quantization for LLM weights?", "INT8 quantization maps fp16 weights to 8-bit integers with per-channel scales, roughly halving memory. INT4 (GGML/GGUF, AWQ) stores weights in 4 bits with grouping and dequantization on-the-fly during matmul, reducing memory by ~75%. GPTQ is a layer-wise quantization method that minimizes error by updating remaining unquantized weights after each layer, offering better accuracy than naive INT4 rounding."),
    ("{lang}: ¿Cómo se calculan los FLOPs necesarios para entrenar un modelo LLM desde cero?", "Los FLOPs de entrenamiento se aproximan como 6 × N × D, donde N es el número de parámetros y D el número total de tokens de entrenamiento. Para un modelo 7B entrenado con 2T tokens: 6 × 7×10^9 × 2×10^12 ≈ 8.4×10^22 FLOPs. En hardware A100 (312 TFLOPS FP16), requiere ~270,000 horas-GPU teóricas."),
    ("{lang}: Qual a diferença entre precisão FP16, BF16 e FP32 no treinamento de redes neurais?", "FP32 usa 32 bits com grande range e precisão. FP16 reduz pela metade, acelerando matmuls em GPUs Tensor Core, mas sofre de underflow/overflow. BF16 (Brain Float) mantém o mesmo range exponencial de FP32 mas com metade da mantissa, sendo mais estável que FP16 para treinamento com quase o mesmo custo computacional."),
    ("{lang}: Décris le fonctionnement de LoRA (Low-Rank Adaptation) pour le fine-tuning efficace des LLMs.", "LoRA injecte des matrices de décomposition de rang faible (A et B) dans les projections d'attention. Au lieu de mettre à jour W (d×d), on apprend ΔW = BA où B est d×r et A est r×d avec r << d. Cela réduit le nombre de paramètres entraînables de 99.9%. En inférence, les matrices BA peuvent être fusionnées dans W sans surcharge latence."),
    ("{lang}: Spiega come funziona l'offloading della VRAM su RAM/disco in llama.cpp per eseguire modelli grandi su GPU limitate.", "llama.cpp supporta l'offload selettivo dei layer del transformer sulla GPU (via flag -ngl). I layer non offloaded rimangono sulla RAM/CPU. In assenza di RAM sufficiente, utilizza lo swapping su disco (mmap) con penalità di latenza. È possibile bilanciare -ngl per trovare il punto ottimo tra velocità e memoria disponibile."),
    ("{lang}: Wie berechnet man den Arbeitsspeicherbedarf (VRAM) für das Training eines 13B-Modells mit Adam-Optimizer und Batch-Größe 1?", "Adam speichert 2 Zustände pro Parameter (momentum und variance). Bei fp32 Training: 4 Bytes × Parameter × 4 (Modell + Gradienten + 2 Optimizer-Zustände) = ~208 GB für 13B. Mixed precision (fp16/fp32) reduziert dies auf ~104 GB. Mit ZeRO-Stage-3 (DeepSpeed) wird dies über mehrere GPUs partitioniert."),
    ("{lang}: Explica qué son los 'expertos' en una arquitectura Mixture of Experts (MoE) como Mixtral.", "En MoE, solo un subconjunto de parámetros se activa por token. Mixtral 8x7B tiene 8 'expertos' de 7B parámetros cada uno, pero un router selecciona los top-2 expertos por token. Esto significa que los FLOPs por token son similares a un modelo 7B denso, mientras que la capacidad total de parámetros es ~47B activando ~13B por token."),

    # Tool Calling / Agents
    ("{lang}: How does OpenAI's function calling format work, and what are best practices for schema design?", "The model receives a 'tools' array with JSON schemas (name, description, parameters). When it decides to call a tool, it emits a special message with 'tool_calls' containing the function name and JSON arguments. Best practices: write precise descriptions (they act as prompts), use enums for constrained choices, mark required fields, and keep schemas minimal to reduce token usage."),
    ("{lang}: ¿Cómo implementar un bucle ReAct (Reasoning + Acting) para un agente que use herramientas externas?", "El bucle ReAct alterna entre Thought, Action y Observation. En cada iteración, el LLM razona sobre qué herramienta usar (Thought), genera una llamada JSON (Action), el sistema ejecuta la herramienta y devuelve el resultado (Observation). El historial completo se reinyecta en el prompt hasta que el modelo emite la respuesta final."),
    ("{lang}: O que é 'JSON mode' em LLMs e qual sua relação com tool calling?", "JSON mode força o modelo a gerar apenas JSON válido, sem texto explicativo. É útil para extração estruturada quando não há ferramentas externas. Tool calling vai além: o modelo escolhe entre múltiplas funções, fornece argumentos validados por schema, e o sistema gerencia o loop de execução. JSON mode é um componente, mas não substitui a orquestração de agentes."),
    ("{lang}: Comment gérer les erreurs d'appel d'outils (timeout, exceptions) dans une architecture d'agent LLM?", "Stratégies: 1) Retry exponentiel avec jitter. 2) Retourner l'erreur au LLM comme Observation pour qu'il réagisse ('L'API météo a échoué, je vais utiliser le cache'). 3) Circuit breaker pour éviter les cascades. 4) Fallback tools (cache local, moteur de recherche secondaire). L'agent doit toujours recevoir le contexte d'erreur, pas un simple crash."),
    ("{lang}: Scrivi un esempio di schema JSON per una tool 'search_database' usata da un agente AI.", '{\n  "type": "function",\n  "function": {\n    "name": "search_database",\n    "description": "Search the product catalog by keyword and price range.",\n    "parameters": {\n      "type": "object",\n      "properties": {\n        "query": {"type": "string", "description": "Search keyword"},\n        "min_price": {"type": "number"},\n        "max_price": {"type": "number"},\n        "category": {"type": "string", "enum": ["electronics", "clothing", "books"]}\n      },\n      "required": ["query"]\n    }\n  }\n}'),
    ("{lang}: Cum se poate preveni 'hallucinarea' unui agent AI atunci când apelează funcții?", "1) Constrângeri stricte de schema JSON și validare de intrare. 2) Grounding: obligă agentul să citeze surse înainte de a genera argumente. 3) Tool confirmation: pentru acțiuni distructive (scriere, ștergere), solicită confirmare umană. 4) Self-consistency: generează multiple răspunsuri și votează cel mai frecvent. 5) Logging exhaustiv pentru audit și debug."),

    # Data Centers / Infrastructure
    ("{lang}: What is the difference between Data Parallelism, Tensor Parallelism, and Pipeline Parallelism in distributed LLM training?", "Data Parallelism (DP) replicates the model across GPUs and splits the batch; each GPU processes a subset and gradients are averaged. Tensor Parallelism (TP) splits individual layers (matmuls) across GPUs within the same node, essential for fitting large layers in memory. Pipeline Parallelism (PP) splits the model by layers across GPUs, feeding micro-batches through a pipeline to reduce idle time (bubbles). Modern training combines all three (3D parallelism)."),
    ("{lang}: ¿Qué es el PUE (Power Usage Effectiveness) y por qué es crítico en un data center de IA?", "PUE = Energía total del data center / Energía consumida por equipos informáticos. Un PUE de 1.0 sería perfecto (sin overhead). Los mejores centros alcanzan 1.1-1.2 usando refrigeración líquida, free cooling con aire exterior, y energía renovable. Dado que clusters de IA consumen decenas de megavatios, mejorar el PUE reduce costes operativos y huella de carbono masivamente."),
    ("{lang}: Explique a arquitetura de um cluster de GPUs H100 interconectadas por InfiniBand.", "Clusters de treinamento usam nós DGX H100 com 8 GPUs NVLink-interconectadas internamente (900 GB/s). Entre nós, switches InfiniBand NDR 400 Gbps formam uma rede full-bisection bandwidth. Otimizar a topologia de rede é crucial: all-reduce coletivos devem saturar os links sem hotspots. RoCEv2 sobre Ethernet é uma alternativa mais barata, mas com maior latência e jitter."),
    ("{lang}: Quelle est la consommation énergétique typique d'un cluster de 1024 GPUs H100 et comment la réduire?", "Un H100 consomme ~700W (TDP). Un cluster de 1024 unités représente ~715 kW continus, soit ~6.3 GWh/an si utilisé 24/7. Réduction: 1) Utiliser des instances spot/cloud pour l'entraînement tolérant aux interruptions. 2) Mixed precision et quantification pour moins de cycles. 3) Refroidissement liquide direct-to-chip qui améliore le PUE. 4) Planification de tâches pour maximiser l'utilisation GPU (pas de idle)."),
    ("{lang}: Descrivi l'architettura di un data center moderno per l'addestramento di LLM con focus sul raffreddamento.", "I data center HPC adottano raffreddamento a liquido (Direct Liquid Cooling): il refrigerante scorre attraverso cold plate direttamente sulle GPU e CPU. Questo riduce il PUE a 1.03-1.08 rispetto all'aria tradizionale (1.4+). Le torri di raffreddamento usano acqua ricircolata. In climi freddi, l'economizer ad aria esterna ('free cooling') riduce ulteriormente il consumo energetico."),
    ("{lang}: Care sunt avantajele și dezavantajele utilizării Kubernetes pentru orchestrarea inferenței LLM în producție?", "Avantaje: auto-scaling pe baza de load, self-healing, și gestionarea uniformă a deploymenturilor. Dezavantaje: overhead de rețea și latență pentru inferență real-time; Kubernetes nu este nativ conceput pentru scheduling de GPU cu fragmentare de memorie. Soluții: KubeRay pentru clusterizare, Triton Inference Server ca backend, și node pools dedicate pentru GPU."),
    ("{lang}: Wie funktioniert 'speculative decoding' zur Beschleunigung der LLM-Inferenz?", "Beim spekulativen Decoding generiert ein kleines 'Draft'-Modell (z.B. 1B) mehrere Tokens sequentiell. Das große 'Target'-Modell (z.B. 70B) verifiziert alle Draft-Tokens parallel in einem Forward-Pass. Wenn die Tokens akzeptiert werden, spart man die Latenz des großen Modells. Der Speedup hängt von der Akzeptanzrate des Draft-Modells ab und erfordert geteilte KV-Caches."),

    # Inference Optimization / Serving
    ("{lang}: What is 'continuous batching' in vLLM and how does it improve throughput compared to static batching?", "Static batching waits for all sequences in a batch to finish before starting a new batch, causing GPU idle time when sequences have different lengths. Continuous batching (in-flight batching) in vLLM dynamically replaces completed sequences with new requests at every forward pass. This keeps the GPU fully utilized and can improve throughput by 10-20x, especially with variable output lengths."),
    ("{lang}: ¿Qué es FlashAttention y por qué reduce tanto el uso de memoria HBM durante el entrenamiento?", "FlashAttention recalcula la atención en bloques (tiling) que caben en la SRAM rápida de la GPU, evitando materializar la matriz de atención completa (N×N) en la HBM lenta. Reduce la complejidad de memoria de O(N²) a O(N), permitiendo secuencias más largas y acelerando el entrenamiento hasta 2-4× en GPUs modernas."),
    ("{lang}: Como o 'prefix caching' do vLLM acelera a inferência de prompts com contexto compartilhado?", "Múltiplas requisições podem compartilhar o mesmo prefixo (ex: system prompt + documento RAG). O prefix caching armazena os KV caches computados desse prefixo comum e reutiliza para novas requisições, evitando recomputação. Isso reduz drasticamente o Time-To-First-Token (TTFT) em cargas de trabalho com contexto repetido."),
    ("{lang}: Quels sont les avantages de TensorRT-LLM par rapport à l'inférence PyTorch native pour les modèles de production?", "TensorRT-LLM compile le graphe de modèle en un moteur CUDA optimisé avec fusion de kernels (attention, activation, layernorm), support de FP8/INT4, et gestion efficace du KV cache en paged memory. Il offre une latence bien inférieure et un débit supérieur par rapport à PyTorch eager mode, au prix d'un temps de compilation et d'une flexibilité réduite."),
    ("{lang}: Come ottimizzare la latenza di un modello LLM in produzione usando quantization e kernel fusion?", "1) Quantizzazione a INT8/FP8 con TensorRT-LLM o vLLM per ridurre memory bandwidth. 2) Fusione dei kernel: combinare linear+activation+layernorm in un unico kernel CUDA per minimizzare round-trip HBM. 3) Batch size dinamico con continuous batching. 4) Speculative decoding per saltare forward passes del modello grande. 5) Colocazione del modello su GPU con NVLink per all-reduce veloce."),
    ("{lang}: Ce este 'KV cache quantization' și cum afectează calitatea generării?", "KV cache quantization reducează precizia tensorilor key/value de la fp16/bf16 la INT8 sau FP8. Deoarece KV cache-ul consumă majoritatea VRAM-ului în secvențe lungi, aceasta permite batch-uri mai mari și secvențe mai lungi. Impactul asupra calității este minim (<1% perplexity increase) deoarece valorile de atenție au dinamic range mai mic decât greutățile modelului."),

    # Training / Fine-tuning
    ("{lang}: Explain the difference between SFT (Supervised Fine-Tuning) and RLHF (Reinforcement Learning from Human Feedback).", "SFT trains the model on high-quality input-output pairs using standard next-token prediction loss. RLHF goes further: after SFT, a reward model is trained on human preference rankings (which response is better), then PPO reinforcement learning optimizes the policy to maximize the reward while staying close to the SFT model via a KL divergence penalty."),
    ("{lang}: ¿Cómo afecta el 'gradient accumulation' al entrenamiento de LLMs con memoria GPU limitada?", "Gradient accumulation divide un batch lógico grande en micro-batches pequeños que caben en VRAM. Los gradientes se acumulan (suman) a través de múltiples forward/backward passes antes de actualizar los pesos. Esto permite simular batch sizes grandes (efectivos) sin requerir proporcionalmente más memoria, a costa de un entrenamiento más lento por step."),
    ("{lang}: O que é 'checkpointing de ativação' (activation checkpointing) e como economiza memória?", "Em vez de armazenar todas as ativações intermediárias para o backward pass, o activation checkpointing salva apenas as entradas de certas camadas. Durante o backward, recalcula as ativações sob demanda. Troca computação por memória: reduz o footprint de VRAM em ~30-50% ao custo de ~20% mais FLOPs de treinamento."),
    ("{lang}: Décris l'algorithme DPO (Direct Preference Optimization) et pourquoi il remplace souvent RLHF.", "DPO optimise directement la politique à partir de paires de préférences humaines sans modèle de récompense explicite. Il reformule l'objectif RLHF en une perte de classification binaire sur les préférences, évitant l'instabilité de PPO. DPO est plus simple à implémenter, plus rapide à entraîner, et produit souvent des résultats comparables ou supérieurs à RLHF classique."),
    ("{lang}: Come si sceglie il learning rate durante il fine-tuning di un LLM pre-addestrato?", "Per LLM grandi, i learning rate di fine-tuning sono tipicamente 10-100× più piccoli del pre-training (es. 1e-5 vs 1e-3). Si usa warm-up per i primi 1-5% degli step, poi cosine decay. LoRA richiede LR leggermente più alti (1e-4). Monitorare la training loss e la validation perplexity; un LR troppo alto causa catastrophic forgetting, troppo basso underfitting."),
    ("{lang}: Care este diferența dintre 'full fine-tuning' și 'parameter-efficient fine-tuning' (PEFT)?", "Full fine-tuning actualizează toți parametrii modelului și necesită VRAM proporțional cu dimensiunea modelului. PEFT (LoRA, QLoRA, prefix tuning) actualizează doar un subset mic de parametri (0.1-1%). QLoRA combină quantizarea de 4 biți a modelului de bază cu LoRA în fp16, permițând fine-tuning de modele 70B pe o singură GPU consumer de 24 GB."),
    ("{lang}: Erkläre die Funktion von 'learning rate schedulers' wie cosine annealing und warm restarts.", "Cosine Annealing reduziert die learning rate nach einer Kosinuskurve, was sanftere Konvergenz als stufenweises Decay ermöglicht. Warm Restarts (SGDR) setzen die LR periodisch auf den Ausgangswert zurück, was dem Optimierer erlaubt, lokale Minima zu verlassen. In modernem LLM-Training werden oft lineare Warmup-Phasen mit anschließendem Cosine-Decay kombiniert."),

    # Multimodal / Safety / Alignment
    ("{lang}: How does a vision encoder like CLIP interact with an LLM in a multimodal model such as LLaVA?", "CLIP converts images into a sequence of patch embeddings. In LLaVA, a lightweight projection layer (MLP) maps these visual embeddings into the LLM's token embedding space. The model is then fine-tuned on image-text instruction data so the LLM learns to attend to visual tokens as if they were text tokens, enabling visual question answering."),
    ("{lang}: ¿Qué es el 'reward hacking' en el entrenamiento con RLHF y cómo se mitiga?", "Reward hacking ocurre cuando el modelo explota fallas en el reward model para obtener alta puntuación sin cumplir la intención real. Ejemplo: generar respuestas largas y confiadas porque el reward model favorece la longitud. Mitigación: entrenar reward models más robustos con datos adversariales, usar penalización KL para mantener cercanía al modelo SFT, y evaluar con métricas humanas fuera de la distribución de entrenamiento."),
    ("{lang}: O que é 'constitutional AI' e como difere do RLHF tradicional?", "Constitutional AI (Anthropic) usa um conjunto de princípios ('constituição') para auto-corrigir o modelo. Em vez de feedback humano direto, o modelo gera respostas, critica a si mesmo com base nos princípios, e refina. O RLHF tradicional depende de anotadores humanos; Constitutional AI reduz a dependência de anotação humana e pode escalar alinhamento mais rapidamente."),
    ("{lang}: Comment fonctionne le 'red teaming' automatisé pour évaluer la sécurité d'un LLM?", "Le red teaming automatise la génération de prompts adversariaux (jailbreaks, injections, contenus toxiques) via un modèle attaquant qui optimise pour provoquer des comportements interdits. Techniques: PAIR (Prompt Automatic Iterative Refinement), TAP (Tree of Attacks). Les réponses sont évaluées par un classifieur de sécurité. Cela permet de découvrir des vulnérabilités à grande échelle avant le déploiement."),
    ("{lang}: Descrivi il problema del 'catastrophic forgetting' durante il fine-tuning di un LLM e una soluzione.", "Il catastrophic forgetting si verifica quando il modello, addestrato su un nuovo task, perde prestazioni sui task precedenti. Soluzione: replay di dati originali mescolati ai nuovi dati di fine-tuning (mixed fine-tuning). In alternativa, tecniche PEFT come LoRA riducono la perturbazione dei pesi originali, preservando meglio la conoscenza pre-addestrata."),
    ("{lang}: Cum se evaluează calitatea unui model de limbaj folosind benchmark-uri precum MMLU sau HumanEval?", "MMLU (Massive Multitask Language Understanding) testează cunoștințe academice pe 57 de domenii prin întrebări cu variante multiple. HumanEval evaluează capacitatea de generare de cod Python prin teste unitare. Aceste benchmark-uri oferă metrici standardizate, dar au limitări: pot conține date de antrenament contaminate și nu măsoară competențe sociale sau creative ale modelului."),
    ("{lang}: Was ist der Unterschied zwischen 'emergent abilities' und 'capabilities' bei großen Sprachmodellen?", "Capabilities sind trainierte Fähigkeiten wie Grammatik oder Übersetzung, die kontinuierlich mit der Modellgröße wachsen. Emergent abilities sind Fähigkeiten, die scheinbar abrupt ab einer bestimmten Skala auftreten (z.B. Chain-of-Thought Reasoning, In-Context Learning). Sie entstehen durch die Interaktion simpler Trainingsziele mit massiver Parameteranzahl und Datenvolumen."),

    # Misc AI / Hardware intersection
    ("{lang}: How do you calculate the inference throughput (tokens/sec) for a given model on a specific GPU?", "Throughput depends on memory bandwidth (for memory-bound inference of large models) or compute (for small models). For a quantized 70B model on an A100 (2 TB/s memory bandwidth): each token requires loading all parameters (70B × 0.5 bytes = 35 GB), so theoretical max ≈ 2 TB/s ÷ 35 GB/token ≈ 57 tok/s. Actual throughput is lower due to KV cache bandwidth, attention computation, and overhead."),
    ("{lang}: ¿Cuál es el impacto del 'batch size' en la latencia y el throughput de la inferencia de LLMs?", "Batch size 1 minimiza la latencia por solicitud (TTFT bajo) pero subutiliza la GPU. Aumentar el batch size mejora el throughput global (tokens/segundo agregados) porque amortiza el costo fijo de cargar pesos en memoria. Sin embargo, aumenta la latencia percepción para cada usuario. El batch size óptimo depende del SLA de latencia y del tamaño del KV cache disponible."),
    ("{lang}: Explique a arquitetura de um TPU (Tensor Processing Unit) e por que ela é eficiente para treinamento de transformers.", "A TPU v4 consiste em um array systolic de 65.536 unidades multiply-accumulate (MXU) organizadas em uma malha 2D. Diferente de GPUs genéricas, TPUs são otimizadas para operações densas de matmul com precisão bfloat16. A comunicação entre TPUs usa interconexões toroidais (ICI) de alta largura de banda, ideais para all-reduce coletivos em treinamento distribuído de LLMs."),
    ("{lang}: Quels sont les défis du déploiement de modèles LLM sur des edge devices (smartphones, IoT)?", "Contraintes: VRAM limitée (4-16 GB), batterie, et absence de connectivité réseau. Solutions: quantization INT4/INT8 avec GGML/ExecuTorch, distillation vers des modèles plus petits (MobileLLM), et découpage du modèle (exécuter l'encodeur sur l'edge et le décodeur dans le cloud). Les NPU dédiées (Apple Neural Engine, Qualcomm Hexagon) accélèrent l'inférence via graph optimization."),
    ("{lang}: Come funziona il meccanismo di 'attention' in un transformer e qual è la sua complessità computazionale?", "L'attention calcola matrici Query, Key, Value tramite proiezioni lineari. Lo score di attenzione è softmax(QK^T / sqrt(d_k)). La complessità è O(n² × d) dove n è la lunghezza della sequenza e d la dimensione del modello. Questo quadratica rende costoso il processing di sequenze molto lunghe, motivando tecniche come FlashAttention, sparse attention e linear attention."),
    ("{lang}: Ce sunt 'embeddings' și cum sunt folosiți în căutarea semantică (RAG)?", "Embeddings sunt vectori densi de dimensiune fixă (ex. 768, 1536) care reprezintă semantic conținutul textual. Modele precum BGE sau OpenAI text-embedding-ada calculează acești vectori. În RAG, textele sursă sunt indexați într-o bază de date vectoriale (FAISS, Pinecone, Qdrant). Interogarea utilizatorului este transformată în embedding și se caută cei mai apropiați vecini (k-NN) pentru a recupera context relevant."),
    ("{lang}: Wie wirkt sich die Sequenzlänge auf den Speicherbedarf der Attention-Schicht aus?", "Der Speicherbedarf der Attention wächst quadratisch mit der Sequenzlänge: für Länge N und Batch B benötigt man O(B × N² × heads) Speicher für die Attention-Matrix. Bei einer Sequenzlänge von 128k Tokens und Batch 1 kann das leicht Dutzende Gigabyte an VRAM erfordern. Methoden wie FlashAttention und sparse Attention reduzieren diesen Bedarf drastisch."),
    ("{lang}: Explica el concepto de 'model distillation' para comprimir un LLM grande en uno pequeño.", "La destilación entrena un modelo 'student' (pequeño) para imitar las salidas del modelo 'teacher' (grande), no solo las etiquetas duras sino las distribuciones de probabilidad (soft targets) y los logits intermedios. Esto transfiere conocimiento implícito sobre relaciones entre clases. Variantes como SeqKD aplican esto a transformers, permitiendo modelos de 1B que imitan comportamiento de 70B con pérdida mínima."),
    ("{lang}: O que são 'hallucinations' em LLMs e quais técnicas reduzem sua ocorrência?", "Hallucinations são gerações plausíveis mas factualmente incorretas. Causas: memorização errônea, extrapolação além dos dados de treino, ou atenção dispersa. Técnicas de redução: RAG com grounding em fontes verificáveis, fine-tuning com dados de alta qualidade, constrained decoding (forçar saídas baseadas em fatos), e verificação multi-pass (gerar e depois verificar com um segundo modelo)."),
    ("{lang}: Comment mesurer la 'perplexity' d'un modèle de langage et qu'est-ce qu'une bonne valeur?", "La perplexité est définie comme exp(-1/N × Σ log P(token_i | context)). C'est la moyenne géométrique inverse de la probabilité assignée par le modèle à chaque token. Une perplexité plus basse indique une meilleure prédiction. Sur WikiText-103, un bon LLM atteint ~10-15; GPT-4 atteint des scores encore plus bas. Cependant, une perplexité basse ne garantit pas la qualité des réponses ou la factualité."),
]

# Expand to 100 items by cycling templates with language variations
ai_tasks = []
seen_ai = set()
while len(ai_tasks) < 100:
    for template in ai_templates:
        if len(ai_tasks) >= 100:
            break
        lang = langs[len(ai_tasks) % len(langs)]
        q = template[0].format(lang=lang)
        r = template[1]
        if q in seen_ai:
            q = f"[{len(ai_tasks)}] {q}"
        seen_ai.add(q)
        ai_tasks.append((q, r))

for i in range(100):
    idx = 424 + i
    q, r = ai_tasks[i]
    write_json(idx, q, r)

print("Generated AI/LLM sample files 424-523 successfully.")
